# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybfNm8zdTF6tzGqr0db14jlbLkdjXOlQ
"""

import streamlit as st 
from sentence_transformers import SentenceTransformer, util
from PIL import Image

def similarity_scorer(text1,text2):
     model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
     #Compute embedding for 2 sentences
     vector_1= model.encode(text1, convert_to_tensor=True)
     vector_2 = model.encode(text2, convert_to_tensor=True)
     score=float(util.pytorch_cos_sim(vector_1, vector_2))
     if score>1:
        score=1
     return score


def main():
    st.title("Similarity Checker")
    html_temp = """
    <div style="background-color:tomato;padding:10px">
    <h2 style="color:white;text-align:center;">Streamlit Sentence Similarity Scorer </h2>
    </div>
    """
    st.markdown(html_temp,unsafe_allow_html=True)
    text1 = st.text_input("text1")
    text2 = st.text_input("text2")
    
    result=""
    if st.button("Calculate"):
        result=similarity_scorer(text1,text2)
    st.success(result)
    if st.button("About"):
        st.text("Made for Precily")
        st.text("Built with Streamlit")

if __name__=='__main__':
    main()
